var mainPage = angular.module("mainPage", ['ui.router']);
mainPage.config(function($stateProvider, $urlRouterProvider){
	$urlRouterProvider.otherwise("/signin");
	$stateProvider
	.state('signin',{
		url:'/signin',
		controller:'signinCtrl',
		templateUrl:'views/signin.html'
	})
	.state('signup',{
		url:'/signup',
		templateUrl:'views/signup.html',
		controller:'signupCtrl'
	})
	.state('dashboard',{
		url:'/dashboard',
		templateUrl:'views/dashboard.html',
		controller:'dashboardCtrl'
	})
	.state('dashboard.user',{
		url:'/user-dashboard',
		templateUrl:'views/user.html'
	})
	.state('dashboard.insurance',{
		url:'/insurance-dashboard',
		templateUrl:'views/insurance.html'
	})
	.state('dashboard.admin',{
		url:'/admin-dashboard',
		templateUrl:'views/admin.html'
	})
});